import { isNumber, not, nullish, padStringLeft } from './Util.js';
import { valueAndType } from './debug.js';
import { randInt } from './random.js';
import { sort } from './sort.js';

/** Returns a new array containing the argument, or a clone of
 * the argument if it was already an array.
 *
 * @template T
 * @param {T | T[]} maybeArray
 * @returns {T[]} A (shallow) clone of input array, or a new array containing the input value.
 */
export function ensureArray(maybeArray) {
  if (maybeArray === null || maybeArray == undefined) return [];
  if (Array.isArray(maybeArray)) return [...maybeArray];
  return [maybeArray];
}

/** Creates a new blank array with the specified dimension(s).
 *
 * @param {...number} length
 * @returns {Array}
 */
export function array(length) {
  const arr = new Array(length || 0);

  if (arguments.length > 1) {
    const args = Array.prototype.slice.call(arguments, 1);

    let i = length;
    while (i--) arr[length - 1 - i] = array.apply(this, args);
  }

  return arr;
}

/** Resets all members of a multidimensional array to the provided value.
 * (If that value is an object, all references will point to the SAME object.
 *  Consider using the fillClone method instead, in that case.)
 *
 * @template T
 * @param {*[]} arr
 * @param {T} value
 * @returns {T[]} The input array, mutated.
 */
export function fill(arr, value) {
  for (let i = 0; i < arr.length; i++) {
    if (Array.isArray(arr[i])) {
      fill(arr[i], value);
    } else {
      arr[i] = value;
    }
  }

  return arr;
}

/**
 * Resets all members of a multidimensional array to clones of the provided template.
 * 
 * @template T
 * @param {*[]} arr
 * @param {T} template
 * @returns {T[]} The input array, mutated.
 */
export function fillClone(arr, template) {
  for (let i = 0; i < arr.length; i++) {
    if (Array.isArray(arr[i])) {
      fillClone(arr[i], template);
    } else {
      arr[i] = structuredClone(template);
    }
  }

  return arr;
}

/** Resets all members of a multidimensional array to the value generated by the provided function.
 *
 * @template T
 * @param {*[]} arr
 * @param {(number) => T} generatorFn
 * @returns {T[]} The input array, mutated.
 */
export function fillFrom(arr, generatorFn) {
  for (let i = 0; i < arr.length; i++) {
    if (Array.isArray(arr[i])) {
      fillFrom(arr[i], generatorFn);
    } else {
      arr[i] = generatorFn();
    }
  }

  return arr;
}

export const prettyFormat2DRectArray = (function () {
  function toString(value, printAsBlank) {
    if (value === null || value === undefined) return '.';
    if (printAsBlank.includes(value)) return '.';

    try {
      return value.toString();
    } catch {
      return value + '';
    }
  }

  return function prettyFormat2DRectArray(array, ...printAsBlank) {
    array = array.filter(not(nullish));

    let longest = 0;
    for (let x = 0; x < array.length; x++) {
      if (!array[x]) continue;
      for (let y = 0; y < array[x].length; y++) {
        const stringOf = toString(array[x][y], printAsBlank);
        if (stringOf.length > longest) longest = stringOf.length;
      }
    }

    let prettyPrint = '\n';

    let initialX = 0;
    while (!array[initialX] && initialX < array.length) initialX++;

    let x = initialX;
    for (let y = array[x].length - 1; y >= 0; y--) {
      for (x = initialX; x < array.length; x++) {
        prettyPrint += padStringLeft(toString(array[x][y], printAsBlank), longest) + ' ';
      }
      prettyPrint += '\n';
    }

    return prettyPrint;
  };
})();

export function prettyPrint2DRectArray(array, ...printAsBlank) {
  console.log(prettyFormat2DRectArray(array, ...printAsBlank));
}

/** Removes zero or more items from an array by index.
 * Mutates the original array.
 *
 * @template T
 * @param {T[]} array
 * @param  {...number} indexes
 * @returns {T[]} A new array containing the removed items in reverse index order.
 */
export function removeMultipleIndexes(array, ...indexes) {
  let ret = [];

  indexes.sort(sort.numeric.descending);

  for (const index of indexes) ret.push(array.splice(index, 1)[0]);

  return ret;
}

/** Returns a new array containing the non-null elements
 * of the target array, even if it is sparse.
 *
 * @param {Array} array
 * @returns {Array}
 */
export function compactSparseArray(array) {
  return array.filter(function (x) {
    return x != null;
  });
}

/**
 * @template T
 * @param {T[][]} array Arrays nested in arrays arbitrarily-many layers deep. Does not mutate.
 * @param {T[]} [destinationArray] Optional destination array. If provided, elements will be appended to this array.
 * @returns {T[]} An array with all non-Array children, whose elements are the array elements of the root array and subarrays, in depth-first-traversal order.
 */
export function flatten(array, destinationArray = []) {
  const length = array.length;

  for (let i = 0; i < length; i++) {
    const value = array[i];

    if (Array.isArray(value)) {
      flatten(value, destinationArray);
    } else {
      destinationArray.push(value);
    }
  }

  return destinationArray;
}

/**
 * @param {number[]} array
 * @returns {number} The total of the numeric array, ignoring any non-numbers. Zero if no numbers are present.
 */
export function sum(array) {
  let total = 0;

  for (let i = 0; i < array?.length; i++) {
    if (isNumber(array[i])) total += array[i];
  }

  return total;
}

/**
 * @param {number[]} array
 * @returns {number} The product of the numeric array, ignoring any non-numbers. One if no numbers are present.
 */
export function product(array) {
  let product = 1;

  for (let i = 0; i < array?.length; i++) {
    if (isNumber(array[i])) product *= array[i];
  }

  return product;
}

/**
 * @param {number[]} array
 * @returns {number} The arithmetic mean (average) of the numeric array, ignoring any non-numbers.
 */
export function mean(array) {
  return sum(array) / array?.length;
}

/**
 * @param {number[]} array
 * @returns {{ max: number, index: number }?}
 */
export function findMax(array) {
  if (!array.length) return null;

  let max = array[0];
  let index = 0;

  for (let i = 1; i < array.length; i++) {
    if (array[i] > max) {
      max = array[i];
      index = i;
    }
  }

  return { max, index };
}

/**
 * @param {number[]} array1
 * @param {number[]} array2
 * @returns {number[]} A new array containing the memberwise difference of the numeric arrays.
 */
export function memberwiseSubtract(array1, array2) {
  const ret = [];

  for (let i = 0; i < array1.length; i++) {
    ret[i] = array1[i] - array2[i];
  }

  return ret;
}

/**
 * @param {number[]} array1
 * @param {number[]} array2
 * @returns {number[]} A new array containing the memberwise product of the numeric arrays.
 */
export function memberwiseMultiply(array1, array2) {
  const ret = [];

  for (let i = 0; i < array1.length; i++) {
    ret[i] = array1[i] * array2[i];
  }

  return ret;
}

export function transpose(arr) {
  const ret = array(arr[0].length, arr.length);

  for (let x = 0; x < arr.length; x++) {
    for (let y = 0; y < arr[0].length; y++) {
      ret[y][x] = arr[x][y];
    }
  }

  return ret;
}

/**
 * @template T
 * @param {T[]} arr
 * @returns {{ first: T, second: T }[]} An array of all pairs of members in the input array.
 */
export function pairs(arr) {
  const ret = [];

  for (let i = 0; i < arr.length; i++) {
    for (let j = i + 1; j < arr.length; j++) {
      ret.push({
        first: arr[i],
        second: arr[j],
      });
    }
  }

  return ret;
}

/**
 * @param {Record<string, *[]>} arrayMapping
 * @returns {Record<string, *>[]} An array of objects, each containing the elements of the input arrays, mapped by key. Any object which would contain all null values is instead null. The output array will be the length of the array at the first input key.
 * @example
 * {
 *   a: [1, 2, 3],
 *   b: [4],
 *   c: [5, 6]
 * }
 * becomes:
 * [
 *   { a: 1, b: 4,    c: 5 },
 *   { a: 2, b: null, c: 6 },
 *   { a: 3, b: null, c: null },
 * ]
 */
export function zipToObjects(arrayMapping) {
  const keys = Object.keys(arrayMapping);
  const length = arrayMapping[keys[0]].length;

  const ret = [];

  for (let i = 0; i < length; i++) {
    const obj = {};

    let allKeysNull = true;
    for (const key of keys) {
      obj[key] = arrayMapping[key][i];
      if (obj[key] != null) allKeysNull = false;
    }

    if (allKeysNull) ret.push(null);
    else ret.push(obj);
  }

  return ret;
}

/**
 * @param {T[]} arr
 * @returns {T} The first element of the input array.
 */
export function first(arr) {
  return arr[0];
}

/**
 * @param {T[]} arr
 * @returns {T} The last element of the input array.
 */
export function last(arr) {
  return arr.slice(-1)[0];
}

/**
 * @param {number} sizeOrMin The size of the range, or the minimum value of the range if a max was also provided.
 * @param {number} [max] The maximum value of the range.
 * @returns {number[]} A numeric array containing [0, 1, ..., size - 1], or [min, min + 1, ..., max] if a max was provided.
 */
export function range(sizeOrMin, max) {
  let size, start;
  if (max != null) {
    size = max - sizeOrMin + 1;
    start = sizeOrMin;
  } else {
    max = size = sizeOrMin;
    start = 0;
  }

  const ret = array(size);
  for (let i = 0; i < size; i++) ret[i] = i + start;
  return ret;
}

/**
 * @template T
 * @param {T[]} arr
 * @returns {T[]}
 */
export function cloneRectangularArray(arr) {
  const width = arr.length;
  if (width === 0) return [];
  const height = arr[0].length;

  const ret = array(width, height);

  for (let i = 0; i < width; i++) {
    for (let j = 0; j < height; j++) {
      ret[i][j] = arr[i][j];
    }
  }

  return ret;
}

/**
 * @template T
 * @param {T[]} array
 * @param {() => number} randomFunc
 * @returns {T[]} A new array containing the elements of the input array in randomized order.
 */
export function arrShuffle(array, randomFunc = Math.random) {
  return arrShuffleInPlace([...array], randomFunc);
}

/**
 * As I later discovered, this is apparently called the Fisher-Yates shuffle, here invented independently.
 *
 * @template T
 * @param {T[]} array
 * @param {() => number} randomFunc
 * @returns {T[]} The original input array, mutated, in randomized order.
 */
export function arrShuffleInPlace(array, randomFunc = Math.random) {
  for (let i = 0; i < array.length - 1; i++) {
    const swap = randInt(i, array.length - 1, randomFunc);
    if (i !== swap) arrSwap(array, i, swap);
  }

  return array;
}

/** Mutates the input array to swap two items in-place.
 * @param {*[]} array
 * @param {number} i1
 * @param {number} i2
 */
function arrSwap(array, i1, i2) {
  // Tested, found to be performant in the abstract, in bulk.
  // See https://github.com/espoire/performance
  array[i1] = array.splice(i2, 1, array[i1])[0];
}

/**
 * @template T
 * @param {T[]} arr A 2D rectangular array
 * @param {'sunwise' | 'widdershins' | 'turnabout'} direction
 * @returns {T[]} A new 2D rectangular array containing the elements of arr, rotated as indicated.
 */
export function rotateRectangularArray(arr, direction = 'sunwise') {
  const width = arr.length;
  const height = arr[0].length;
  const ret = direction === 'turnabout' ? array(width, height) : array(height, width);

  for (let x = 0; x < width; x++) {
    for (let y = 0; y < height; y++) {
      const { dx, dy } = _getRotatedCoordinates(direction, width, height, x, y);
      ret[dx][dy] = arr[x][y];
    }
  }

  return ret;
}

function _getRotatedCoordinates(direction, width, height, x, y) {
  switch (direction) {
    case 'sunwise':
      return {
        dx: y,
        dy: width - 1 - x,
      };

    case 'widdershins':
      return {
        dx: height - 1 - y,
        dy: x,
      };

    case 'turnabout':
      return {
        dx: width - 1 - x,
        dy: height - 1 - y,
      };

    default:
      throw new Error(
        `rotateRectangularArray() direction argument must be 'sunwise' | 'widdershins' | 'turnabout', given: ${valueAndType(direction)}`
      );
  }
}

/**
 * Recursively crawls the input multidimensional arrays and checks for memberwise equality (===) at each location.
 * No object support, no circular-linking support; subarrays are the only special case.
 *
 * @param {*[]} arr1
 * @param {*[]} arr2
 */
export function memberwiseEquals(arr1, arr2) {
  if (arr1.length !== arr2.length) return false;

  for (let i = 0; i < arr1.length; i++) {
    if (Array.isArray(arr1[i])) {
      if (!Array.isArray(arr2[i])) return false;
      if (!memberwiseEquals(arr1[i], arr2[i])) return false;
    } else if (Array.isArray(arr2[i])) {
      return false;
    } else {
      if (arr1[i] !== arr2[i]) return false;
    }
  }

  return true;
}

/**
 * Checks whether two arrays are "multiset equal", that is:
 * contain all the same elements, including the same number
 * of occurrences of each element, in any order.
 * 
 * Note that object elements are compared by reference, not
 * by value. This means that two different object instances
 * with identical properties will be treated as different.
 *
 * @template T
 * @param {T[]} arr1
 * @param {T[]} arr2
 * @returns {boolean} True if both inputs are arrays which are multiset equal, false otherwise.
 */
export function multisetEquals(arr1, arr2) {
  if (!Array.isArray(arr1) || !Array.isArray(arr2)) return false; // Non-array inputs always treated as not multiset equal
  if (arr1.length !== arr2.length) return false;

  const count = new Map();

  // Construct a map of value:count pairs
  for (const x of arr1) count.set(x, (count.get(x) ?? 0) + 1);

  for (const x of arr2) {
    // If `arr2` contains any elements not in `arr1`, return false
    if (!count.has(x)) return false;

    // Decrement the count for the element, remove key if depleted
    count.set(x, count.get(x) - 1);
    if (count.get(x) === 0) count.delete(x);
  }

  // Check if all keys were removed
  return count.size === 0;
}

/**
 * @template T
 * @param {T[]} arr 
 * @param {(value: T, index: number, array: T[]) => boolean} testFn
 * @returns {number} The number of elements satisfying the test function, or the number of elements present if no testFn is provided.
 */
export function countWhere(arr, testFn) {
  if (testFn == null) return arr.length;

  let total = 0;

  arr.forEach((member, index, array) => {
    if (testFn(member, index, array)) total++;
  });

  return total;
}

/**
 * @param {number[]} arr A sorted number array
 * @param {number} target The number to find
 * @returns {number} The largest array index holding a value at or below the target number, or -1 if no such index exists.
 */
export function findLargestArrayIndexAtOrBelowTarget(arr, target) {
  if (target < arr[0]) return -1;

  let min = 0,
    max = arr.length - 1,
    test,
    passed;

  while (min < max) {
    test = Math.ceil((min + max) / 2);
    passed = arr[test] <= target;
    if (passed) {
      min = test;
    } else {
      max = test - 1;
    }
  }

  return test - !passed;
}

/**
 * @template T
 * @param {T[]} arr
 * @param {null | (a: T, b: T) => boolean} predicate A function which returns true if two elements are considered duplicates. If absent, Set equality is used.
 * @returns {T[]} A new array containing the unique elements of the input array, as defined by the predicate.
 */
export function removeDuplicates(arr, predicate = null) {
  if (predicate == null) return Array.from(new Set(arr));
  const ret = [];

  for (const element of arr) {
    if (!ret.some(existing => predicate(existing, element))) {
      ret.push(element);
    }
  }

  return ret;
}

/**
 * @param {*[]} arr
 * @returns {boolean} True if the provided array contains any pair of duplicate members (as defined by Set equality), false otherwise
 */
export function hasDuplicates(arr) {
  return arr.length !== removeDuplicates(arr).length;
}

/**
 * "Fancy" in that it returns both the element in question and its index.
 * @template T
 * @param {T[]} arr
 * @param {(value: T, index: number, array: T[]) => boolean} predicate
 * @returns {{ element: T, index: number }?}
 */
export function fancyFindLast(arr, predicate) {
  for (let i = arr.length - 1; i >= 0; i--) {
    if (predicate(arr[i], i, arr)) return { element: arr[i], index: i };
  }
}

export function min(arr) {
  return Math.min(...arr);
}

export function max(arr) {
  return Math.max(...arr);
}

/**
 * Returns the largest value found for the given key in the array of objects,
 * or null if no valid values are found.
 *
 * This function skips non-object elements and ignores invalid values (null, undefined, NaN).
 *
 * Usage example:
 *
 * maxByKey('key',   [ { key: 1 }, { key: 2 }, { key: 3 }, { other: 5 } ]) // returns 3
 * maxByKey('other', [ { key: 1 }, { key: 2 }, { key: 3 }, { other: 5 } ]) // returns 5
 * maxByKey('key', [ { key: 1 }, { key: '2' } ]) // returns 1
 * maxByKey('key', [ { key: null }, { key: undefined }, { } ]) // returns null
 * maxByKey('key', [ { key: 1 }, { key: 'invalid' } ]) // returns 1
 *
 * @param {string} key - The key whose value will be compared.
 * @param {Array} arr - The array of objects to search through.
 * @returns {number|null} The largest valid value for the key, or null if no valid values are found.
 */
export function maxByKey(key, arr) {
  let max = null;

  for (const item of arr) {
    // Skip non-object elements (e.g., primitives like strings, numbers)
    if (typeof item !== 'object' || item === null || item[key] == null) continue;

    // Get the value corresponding to the key
    const value = item[key];

    // Skip invalid values (null, undefined, NaN, etc.)
    if (!isNumber(value)) continue;

    // If no valid value has been set or the current value is greater, update max
    if (max === null || value > max) {
      max = value;
    }
  }

  return max;
}

/**
 * Note the reversed parameter order compared to maxByKey().
 * @template T
 * @param {T[]} arr
 * @param {(T) => number} mapFn
 * @returns {{ value: number, element: T, index: number }?} The largest value found by applying the map function to the array elements, or null if no valid values are found.
 */
export function maxByMapFn(arr, mapFn) {
  if (!arr?.length) return null;

  let max = {
    value: null,
    element: null,
    index: null,
  };

  for (let i = 0; i < arr.length; i++) {
    const item = arr[i];

    const value = mapFn(item, i, arr);
    if (!isNumber(value)) continue;

    if (max.value === null || value > max.value) {
      max = {
        value,
        element: item,
        index: i,
      };
    }
  }

  return max;
}

/**
 * @template T
 * @param {T[]} arr
 * @param {(T) => number} mapFn
 * @returns {{ value: number, element: T, index: number }?} The smallest value found by applying the map function to the array elements, or null if no valid values are found.
 */
export function minByMapFn(arr, mapFn) {
  if (!arr?.length) return null;

  let min = {
    value: null,
    element: null,
    index: null,
  };

  for (let i = 0; i < arr.length; i++) {
    const item = arr[i];

    const value = mapFn(item, i, arr);
    if (!isNumber(value)) continue;

    if (min.value === null || value < min.value) {
      min = {
        value,
        element: item,
        index: i,
      };
    }
  }

  return min;
}

/**
 * @template T
 * @param {T[]} arr
 * @param {(a: T, b: T) => number} sortFn
 * @returns {T?} The element which would appear first if the array were sorted by the provided sort function, or null if the array is empty or nullish.
 * Does not mutate the input array.
 */
export function firstBySortFn(arr, sortFn) {
  if (!arr?.length) return null;
  return arr.slice().sort(sortFn)[0];
}

/**
 * @template T
 * @param {T[]} arr
 * @param {(a: T, b: T) => number} sortFn
 * @returns {T?} The element which would appear last if the array were sorted by the provided sort function, or null if the array is empty or nullish.
 * Does not mutate the input array.
 */
export function lastBySortFn(arr, sortFn) {
  if (!arr?.length) return null;
  return arr.slice().sort(sortFn).slice(-1)[0];
}

/**
 * Returns a test function for use with Array.prototype.filter()
 * that filters out elements that are in the provided set.
 * @template T
 * @param  {...T} exceptions
 * @returns {(T) => boolean}
 */
export function except(...exceptions) {
  return function (value) {
    return !exceptions.includes(value);
  };
}

/**
 * @template T
 * @param {T[]} arr
 * @param {(element: T, index: number, array: T[]) => boolean} testFn
 * @returns {number[]} An array of indexes where the test function returns true.
 */
export function indexesWhere(arr, testFn) {
  const indexes = [];

  for (let i = 0; i < arr.length; i++) {
    if (testFn(arr[i], i, arr)) indexes.push(i);
  }

  return indexes;
}

/**
 * @template T
 * @param {T[]} arr
 * @param {(element: T, index: number, array: T[]) => boolean} testFn
 * @returns {number?} The first index where the test function returns true, or null if none found.
 */
export function firstIndexWhere(arr, testFn) {
  for (let i = 0; i < arr.length; i++) {
    if (testFn(arr[i], i, arr)) return i;
  }
  return null;
}

/**
 * @template T
 * @param {T[]} arr
 * @param {(element: T, index: number, array: T[]) => boolean} testFn
 * @returns {number?} The last index where the test function returns true, or null if none found.
 */
export function lastIndexWhere(arr, testFn) {
  for (let i = arr.length - 1; i >= 0; i--) {
    if (testFn(arr[i], i, arr)) return i;
  }
  return null;
}

/**
 * @template T
 * @param {number[]} indexes
 * @param {T[]} arr
 * @param {(T, T) => number} sortFn
 * @returns {number[]} The indexes sorted by the values in the array, using the provided sort function.
 */
export function sortIndexesBy(indexes, arr, sortFn) {
  return indexes.sort((a, b) => sortFn(arr[a], arr[b]));
}

/**
 * @template T
 * @param {number?} count A number of elements to return, or if negative the number of elements to exclude from the tail, or if nullish returns a shallow copy of the entire array.
 * @param {T[]} arr The input array
 * @returns {T[]} The first `count` elements of the input array, or the entire array if it is shorter.
 */
export function head(count, arr) {
  if (count == null) return arr.slice();
  if (count < 0) count += arr.length;
  return arr.slice(0, count ?? 1);
}

/**
 * @template T
 * @param {number?} count A number of elements to return, or if negative the number of elements to exclude from the head, or if nullish returns a shallow copy of the entire array.
 * @param {T[]} arr The input array
 * @returns {T[]} The last `count` elements of the input array, or the entire array if it is shorter.
 */
export function tail(count, arr) {
  if (count == null) return arr.slice();
  if (count < 0) count += arr.length;
  return arr.slice(-count);
}
